Ingredient.destroy_all
Ingredient.create([
  {name: 'allspice'},
  {name: 'almond'},
  {name: 'apple'},
  {name: 'applesauce'},
  {name: 'anchovy'},
  {name: 'artichoke'},
  {name: 'arugula'},
  {name: 'asparagus'},
  {name: 'avocado'},
  {name: 'bacon'},
  {name: 'bagel'},
  {name: 'baked bean'},
  {name: 'baking mix'},
  {name: 'baking soda'},
  {name: 'baking powder'},
  {name: 'balsamic vinegar'},
  {name: 'banana'},
  {name: 'barbeque sauce'},
  {name: 'basil'},
  {name: 'bay leaf'},
  {name: 'beef'},
  {name: 'beet'},
  {name: 'bell pepper'},
  {name: 'black bean'},
  {name: 'black pepper'},
  {name: 'blueberry'},
  {name: 'boullion'},
  {name: 'bread'},
  {name: 'breadcrumb'},
  {name: 'broccoli'},
  {name: 'broth'},
  {name: 'brown sugar'},
  {name: 'brussels sprout'},
  {name: 'butter'},
  {name: 'cabbage'},
  {name: 'canned tuna'},
  {name: 'canola oil'},
  {name: 'carrot'},
  {name: 'cauliflower'},
  {name: 'caramel'},
  {name: 'cheese'},
  {name: 'cherry'},
  {name: 'chicken'},
  {name: 'chickpea'},
  {name: 'chocolate'},
  {name: 'chocolate syrup'},
  {name: 'chili powder'},
  {name: 'chive'},
  {name: 'cinnamon'},
  {name: 'cocoa'},
  {name: 'coconut'},
  {name: 'coconut milk'},
  {name: 'coffee'},
  {name: 'cola'},
  {name: 'collard green'},
  {name: 'corn'},
  {name: 'cornmeal'},
  {name: 'cornstarch'},
  {name: 'corn syrup'},
  {name: 'cottage cheese'},
  {name: 'couscous'},
  {name: 'cucumber'},
  {name: 'cracker'},
  {name: 'cream'},
  {name: 'cream of mushroom'},
  {name: 'dried bean'},
  {name: 'edamame'},
  {name: 'egg'},
  {name: 'eggplant'},
  {name: 'flour'},
  {name: 'garlic'},
  {name: 'ginger'},
  {name: 'gnocchi'},
  {name: 'goat cheese'},
  {name: 'grapefruit'},
  {name: 'grape'},
  {name: 'green bean'},
  {name: 'hazelnut'},
  {name: 'honey'},
  {name: 'hot sauce'},
  {name: 'hummus'},
  {name: 'italian seasoning'},
  {name: 'jalapeno'},
  {name: 'jelly'},
  {name: 'kale'},
  {name: 'ketchup'},
  {name: 'kidney bean'},
  {name: 'kiwi'},
  {name: 'lamb'},
  {name: 'lettuce'},
  {name: 'lemon'},
  {name: 'lentil'},
  {name: 'lime'},
  {name: 'mango'},
  {name: 'maple syrup'},
  {name: 'margarine'},
  {name: 'marinara'},
  {name: 'mayonnaise'},
  {name: 'milk'},
  {name: 'mushroom'},
  {name: 'mustard'},
  {name: 'nutmeg'},
  {name: 'nuts'},
  {name: 'noodle'},
  {name: 'oat'},
  {name: 'oatmeal'},
  {name: 'oil'},
  {name: 'olive oil'},
  {name: 'olive'},
  {name: 'onion'},
  {name: 'orange'},
  {name: 'oregano'},
  {name: 'pancake mix'},
  {name: 'panko'},
  {name: 'paprika'},
  {name: 'parmesan'},
  {name: 'parsley'},
  {name: 'pasta'},
  {name: 'peach'},
  {name: 'peanut butter'},
  {name: 'peanut oil'},
  {name: 'pear'},
  {name: 'pea'},
  {name: 'pecan'},
  {name: 'pesto'},
  {name: 'pickle'},
  {name: 'pineapple'},
  {name: 'pinto bean'},
  {name: 'pita'},
  {name: 'plum'},
  {name: 'polenta'},
  {name: 'popcorn'},
  {name: 'pork'},
  {name: 'potato'},
  {name: 'puff pastry'},
  {name: 'quinoa'},
  {name: 'raisin'},
  {name: 'ranch dressing'},
  {name: 'ravioli'},
  {name: 'relish'},
  {name: 'rice'},
  {name: 'rum'},
  {name: 'sage'},
  {name: 'salmon'},
  {name: 'salsa'},
  {name: 'salt'},
  {name: 'saltine'},
  {name: 'sardine'},
  {name: 'sausage'},
  {name: 'sauerkraut'},
  {name: 'shrimp'},
  {name: 'sour cream'},
  {name: 'soy sauce'},
  {name: 'spinach'},
  {name: 'steak'},
  {name: 'steak sauce'},
  {name: 'stock'},
  {name: 'strawberry'},
  {name: 'sugar'},
  {name: 'syrup'},
  {name: 'tangerine'},
  {name: 'tea'},
  {name: 'thyme'},
  {name: 'tofu'},
  {name: 'tomato'},
  {name: 'tomato paste'},
  {name: 'tomato sauce'},
  {name: 'tuna'},
  {name: 'tortilla'},
  {name: 'turkey'},
  {name: 'vanilla'},
  {name: 'vegetable oil'},
  {name: 'vinegar'},
  {name: 'waffle'},
  {name: 'walnut'},
  {name: 'water'},
  {name: 'watermelon'},
  {name: 'white vinegar'},
  {name: 'worcestershire sauce'},
  {name: 'yam'},
  {name: 'yogurt'},
  {name: 'zucchini'},
  ])
